### ISSUE TITLE
Bad coloring of git-gutter characters, background becomes foreground?

### ISSUE THREAD

**Issue by ZzAntares** [syohex/emacs-git-gutter#141]
Hello, thanks for the work in this great plugin, I'm experiencing a visual problem, lately I've noticed that my git gutter looks like this:

<img width="257" alt="screen shot 2016-12-26 at 23 21 06" src="https://cloud.githubusercontent.com/assets/3653680/21491678/207a8fc6-cbc4-11e6-9f0d-4ea3759d8aac.png">

At first I thought it was the theme (oceanic), but now that I'm trying to correct it I notice there's also happening with other themes that used to look well.

What I'm expecting is that the character `+`, `-` and `~` have the color, instead of them being in a colored square.

This is my setup:
``` elisp
(global-git-gutter-mode +1)
(setq git-gutter:hide-gutter t)

(add-hook 'git-gutter:update-hooks 'magit-after-revert-hook)
(add-hook 'git-gutter:update-hooks 'magit-not-reverted-hook)

(setq git-gutter:modified-sign " ~")
(setq git-gutter:added-sign " +")
(setq git-gutter:deleted-sign " -")
(setq git-gutter:window-width 3)

(set-face-foreground 'git-gutter:modified "#b58900")
(set-face-foreground 'git-gutter:added "#859900")
(set-face-foreground 'git-gutter:deleted "#dc322f")
(set-face-font 'git-gutter:modified "Menlo")
(set-face-font 'git-gutter:added "Menlo")
(set-face-font 'git-gutter:deleted "Menlo")
```

Just as an experiment I've changed the background color:

```
(set-face-background 'git-gutter:modified "#ffffff")
```

And this changes the color of the character, I think there's a switch of `foreground` vs `background` somewhere, tried another fonts and I got the same problem. If it helps this is my emacs version `GNU Emacs 25.1.1 (x86_64-apple-darwin16.3.0, Carbon Version 157 AppKit 1504.76) of 2016-12-16`.

What could be happening?

Thanks for the help!

**Comment by ZzAntares** [comment]
Just for the record I temporarily fixed it exchanging the colors (foreground to background, background to foreground):

``` elisp
(set-face-background 'git-gutter:modified "#b58900")
(set-face-background 'git-gutter:added "#859900")
(set-face-background 'git-gutter:deleted "#dc322f")

(set-face-foreground 'git-gutter:modified "none")
(set-face-foreground 'git-gutter:added "none")
(set-face-foreground 'git-gutter:deleted "none")
```

It looks as good as before.

<img width="256" alt="screen shot 2016-12-27 at 17 10 37" src="https://cloud.githubusercontent.com/assets/3653680/21510343/dbf600b2-cc57-11e6-85a9-1f32476450b9.png">

👍

**Comment by syohex** [comment]
Sorry belated reply. However it looks highlighting with your first configuration on my environment.

![a](https://cloud.githubusercontent.com/assets/554281/22046209/7565f408-dd62-11e6-9fdf-3ef95c941ab5.png)

**Comment by aaronyo** [comment]
I got here via a google search. I was puzzled by a similar background coloring issue. Turned out to just be the result of a theme (zenburn, in my case).

`M-x list-faces-display` will show all loaded faces. Search for git-gutter, select a face (e.g., git-gutter:added) and you may see it marked "THEMED" -- a theme has taken over the styling. You'll need to configure the theme or update the faces after the theme loads.

At any rate, it's likely not something git-gutter is doing -- just some other piece of your emacs init messing with it.

**Comment by ZzAntares** [comment]
Thanks @aaronyo, I've also noticed this in zenburn but I lost interest, until now. Do you mind sharing your fixes? Have you sent a PR to the theme repo?

Another question, how do you "do stuff" after a theme loads? I tend to change themes between sessions depending on ambient light, but there's no hook for it and "hacking" one seems to execute before the theme is fully loaded 🤔.

**Comment by aaronyo** [comment]
Wasn't planning on sending a PR to the theme repo -- I don't think this a bug; just their theme's styling choice.

I'm not all that familiar with themes and what the best practices are, but it makes sense to me to load the theme via the ```load-theme``` function and then, immediately after, add your custom expressions to change faces, etc.

I'm using use-package like so:
```elisp
(use-package zenburn-theme
  :after git-gutter
  :custom
  (git-gutter:modified-sign "▌")
  (git-gutter:added-sign "▌")
  (git-gutter:deleted-sign "▂")
  :init
  (setq zenburn-override-colors-alist
        '(("zenburn-bg"    . window-background)
          ("zenburn-bg-1"  . "#3c3c3c")
          ("zenburn-bg-05" . "#111111")
          ))
  :config
  (load-theme 'zenburn t)
  (custom-theme-set-faces
   'zenburn
   `(highlight ((t (:background , "#444444")))))
  (set-face-inverse-video 'git-gutter:added nil)
  (set-face-inverse-video 'git-gutter:deleted nil)
  (set-face-inverse-video 'git-gutter:modified nil)
  (set-face-background 'git-gutter:added window-background)
  (set-face-background 'git-gutter:deleted window-background)
  (set-face-background 'git-gutter:modified window-background)
  (set-face-foreground 'git-gutter:added "#3f5f3f")
  (set-face-foreground 'git-gutter:deleted "#6f2f2f")
  (set-face-foreground 'git-gutter:modified "#3f3f7f")
 )
```

Since I don't think there is a hook for "theme loaded" or something, if I wanted to switch themes easily and then run customizations, I would make an interactive helper function that first did ```(load-theme my-theme)``` and then my customizations. (note that zenburn allows you to change some things via the zenburn-override-colors-alist which you must setup *before* loading the theme, but this alone doesn't let you get very precise).
